### PR TITLE
Restrict approved developer list

### PR DESCRIPTION
**Pull request by kkellerlbl**
Require authentication and the admin role in order to call list_approved_developers().

### CODE REVIEW

**Comment by MrCreosote** [comment]
One thing that stands out is that the server hasn't been recompiled from the spec, so the authentication mechanisms haven't been added to the server and the username won't be available to the method.

**Comment by kkellerlbl** [comment]
> One thing that stands out is that the server hasn't been recompiled from the spec, so the authentication mechanisms haven't been added to the server and the username won't be available to the method.

Ugh, does the Dockerfile not rebuild those files?  That's frustrating.

**Comment by MrCreosote** [comment]
Actually, maybe it does, I didn't think of that.

**Comment by MrCreosote** [comment]
It's checked in though, so at minimum it's confusing that the spec does not sync up with the server

**Comment by kkellerlbl** [comment]
> Actually, maybe it does, I didn't think of that.

I just verified that the files are not rebuilt, so it's actually a bug and not just confusing.

**Comment by MrCreosote** [comment]
The major thing I see that's missing is a test showing that a user has to have admin perms to call that method

**Comment by kkellerlbl** [comment]
> The major thing I see that's missing is a test showing that a user has to have admin perms to call that method

Good point.  Tests are failing in Travis anyway though.  :(  I think fixing that is well out of scope for this issue.

**Comment by bio-boris** [comment]
Looks good for non authenticated users, but as an admin I still see the same message.

**Comment by MrCreosote** [comment]
Huh, so is the list admins method not tested? based on the 2 commits above, the original changes should've made the tests fail.

**Comment by kkellerlbl** [comment]
> Huh, so is the list admins method not tested? based on the 2 commits above, the original changes should've made the tests fail.

Tests fail in Travis, and I don't have a local mongod, so the tests were never run.

**Comment by kkellerlbl** [comment]
Travis can now run tests, so I can now try to fix the test for list_approved_developers().

**Comment by kkellerlbl** [comment]
Tests now pass, and I've added a test for anonymous and non-admin users.  I'll merge unless I hear objections.

**Pull request merged**
