### PR TITLE
Support for reference data initialization

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by scanon** [comment]
Looking good. It looks like you need a return if the data folder exist. You just have a log right now.

**Comment by rsutormin** [comment]
Good catch! Thanks, Shane. Fixed.

**Comment by rsutormin** [comment]
Forgot to say. Please don't merge this PR before we add two necessary params into CI catalog config!

**Comment by kkellerlbl** [comment]
I've added this to the configuration file:

ref-data-base = /kb/data
kbase-endpoint = https://ci.kbase.us/services

The /kb/data directory doesn't exist on the workers yet though.  Do we need that before merging and redeploying catalog?  (On the workers, I think /kb/data will be a symlink to some sort of shared storage, probably NFS.)

**Comment by rsutormin** [comment]
Nope. Absence of /kb/data should be seen only when you register repo with reference data. So I would merge this PR.

**Comment by kkellerlbl** [comment]
I'm deploying to ci in a few minutes.

**Pull request merged**
