### PR TITLE
Support for unicode chars in module registration (docker build step).

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by MrCreosote** [comment]
Looks ok to me - is this ready to merge now?

**Comment by msneddon** [comment]
@MrCreosote @rsutormin have either of you run tests locally?  I'm trying to run them now.  I'm getting an error (see below), but I seem to be getting it on the develop branch too, so I can't tell if tests were failing there, or I have another problem locally.

Unfortunately, the travis tests stopped working after a Travis-ci VM update that I haven't had time to fix yet.  Tests were passing locally for me recently, but that was still maybe several weeks ago...

```
======================================================================
FAIL: test_full_module_lifecycle (core_registration_test.CoreRegistrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "core_registration_test.py", line 142, in test_full_module_lifecycle
    self.assertTrue(methMissing,'Make sure we did not find the method in NMS under the beta tag')
AssertionError: Make sure we did not find the method in NMS under the beta tag

======================================================================
FAIL: test_local_function_module (local_function_module_test.LocalFunctionModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "local_function_module_test.py", line 56, in test_local_function_module
    self.assertEqual(state['registration'],'complete')
AssertionError: u'error' != 'complete'
```

**Comment by msneddon** [comment]
@MrCreosote if you need this for testing your service, and the failures are from something there already, we can accept now, but it should be high priority to fix these tests.

**Comment by MrCreosote** [comment]
@msneddon no, the changes looked innocuous so I didn't run tests. This is blocking getting the htmlservice up in CI, but I'll let you guys decide what to do.

**Comment by rsutormin** [comment]
I don't think this particular PR has anything to do with test errors we see. So I'm going to merge it and let Mike decide what we should do with tests (I think it may even be some bug in NMS).

**Pull request merged**
